src/objects/Mountains__c.object
<CustomObject>
    <label>Mountains</label>
    <nameField>
        <label>Mountains Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mountains</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Trial__c.object
<CustomObject>
    <fields>
        <fullName>Mountains__c</fullName>
        <label>Mountains</label>
        <referenceTo>Mountains__c</referenceTo>
        <relationshipLabel>Trials</relationshipLabel>
        <relationshipName>Trials</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Trial_Level__c</fullName>
        <label>Trial Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Level 1</fullName>
                </value>
                <value>
                    <fullName>Level 2</fullName>
                </value>
                <value>
                    <fullName>Level 3</fullName>
                </value>
                <value>
                    <fullName>Level 4</fullName>
                </value>
                <value>
                    <fullName>Level 5</fullName>
                </value>
                <value>
                    <fullName>Level 6</fullName>
                </value>
                <value>
                    <fullName>Level 7</fullName>
                </value>
                <value>
                    <fullName>Level 8</fullName>
                </value>
                <value>
                    <fullName>Level 9</fullName>
                </value>
                <value>
                    <fullName>Level 10</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Trial</label>
    <nameField>
        <label>Trial Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestTrialDifficultyExtensionController.cls
/**
 * Created by hstoy on 10/16/2018.
 */

@isTest
private class TestTrialDifficultyExtensionController {

    @isTest static void testController() {

        Mountains__c m = new Mountains__c(Name = 'Test Mountain');
        insert m;

        Trial__c trialTest = new Trial__c(Name = 'Test Trial',
                Mountains__c = m.Id , Trial_Level__c = 'Level 1' );
        insert trialTest;

        PageReference pageReference = Page.TrialDifficultyInformation;
        Test.setCurrentPage(pageReference);

        ApexPages.StandardController sc = new ApexPages.StandardController(trialTest);
        ApexPages.currentPage().getParameters().put('id', trialTest.Id);

        TrialDifficultyExtensionController ex = new TrialDifficultyExtensionController(sc);

        ex.getTrailDetails();
        ex.getColour();

        Trial__c trialTest1 = new Trial__c(Name = 'Test1 Trial',
                Mountains__c = m.Id);
        insert trialTest1;

        sc = new ApexPages.StandardController(trialTest1);
        ApexPages.currentPage().getParameters().put('id', trialTest1.Id);
        ex = new TrialDifficultyExtensionController(sc);
        ex.getTrailDetails();
    }

}