src/objects/Trial__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Trial_Level__c</fullName>
        <label>Trial Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Level 1</fullName>
                </value>
                <value>
                    <fullName>Level 2</fullName>
                </value>
                <value>
                    <fullName>Level 3</fullName>
                </value>
                <value>
                    <fullName>Level 4</fullName>
                </value>
                <value>
                    <fullName>Level 5</fullName>
                </value>
                <value>
                    <fullName>Level 6</fullName>
                </value>
                <value>
                    <fullName>Level 7</fullName>
                </value>
                <value>
                    <fullName>Level 8</fullName>
                </value>
                <value>
                    <fullName>Level 9</fullName>
                </value>
                <value>
                    <fullName>Level 10</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Trial</label>
    <nameField>
        <label>Trial Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Trial_Level__mdt.object
<CustomObject>
    <fields>
        <fullName>Advanced_hiking_equipment_required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Advanced hiking equipment required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Advanced_hiking_footwear_required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Advanced hiking footwear required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Colour__c</fullName>
        <description>Trial Level colour in hex value</description>
        <label>Colour</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Difficulty_Level__c</fullName>
        <label>Experience Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Beginner</fullName>
                    <default>true</default>
                    <label>Beginner</label>
                </value>
                <value>
                    <fullName>Moderate</fullName>
                </value>
                <value>
                    <fullName>Advanced</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Dogs_allowed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Dogs allowed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Experienced_hikers_only__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Experienced hikers only</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>For_Beginners__c</fullName>
        <defaultValue>false</defaultValue>
        <label>For Beginners</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Kids_allowed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Kids allowed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Water_required__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Water required</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/classes/TrialDifficultyExtensionController.cls
public with sharing class TrialDifficultyExtensionController {


    private Trial__c currentTrial;
    private Trial_Level__mdt[] trialLevel;

    public TrialDifficultyExtensionController(ApexPages.StandardController controller) {
        this.currentTrial = [
                SELECT Id, Trial_Level__c
                FROM Trial__c
                WHERE Id = :ApexPages.currentPage().getParameters().get('id')
        ];

    }

    /*
        @Description: The method finds a metaData object by criteria that is set
        from the current record page "Trial_Level__c" field

        @param: currentTrail - stores Id and Trial_Level__c of the current Trail__c's record
                trialLevel - stores all fields of the Trial_Level__mdt

        @Returns: method returns list of the searched fields of the metaData object;
    */
    public Trial_Level__mdt[] getTrailDetails() {
        if (this.currentTrial.Trial_Level__c == null || this.currentTrial.Trial_Level__c == '--None--') {
            return this.trialLevel;
        }
        this.trialLevel = [
                SELECT Advanced_hiking_equipment_required__c, Advanced_hiking_footwear_required__c, Colour__c, Description__c,
                        Dogs_allowed__c, Experienced_hikers_only__c, Difficulty_Level__c, For_Beginners__c,
                        Kids_allowed__c, Water_required__c
                FROM Trial_Level__mdt
                WHERE Label = :this.currentTrial.Trial_Level__c
        ];

        return this.trialLevel;
    }


    /*
        @Description:  The method finds a metaData object by criteria that is set
        from the current record page "Trial_Level__c" field and gets the metaData object's field
        "Colour__c" value. Then it convert it into hexadecimal code.
        
        @param: chars - it is a list of all chars needed to convert the given number from "Colour__c" value
                colourValue - is a list where the "Colour__c" value is stored
                reminder - is an Integer value where modulo division is stored
                temp - temporary String variable where the value of colourValue is stored and processed
                colourValueInteger - an Integer variable is where the temp processed value is stored
                hexString = is a String variable where the hexadecimal code is stored

        @returns: String representation of the hexadecimal value
     */
    public String getColour() {
        String[] chars = new String[]{
                '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f'
        };

        Trial_Level__mdt[] colourValue = [
                SELECT Colour__c
                FROM Trial_Level__mdt
                WHERE Label = :this.currentTrial.Trial_Level__c
        ];

        Integer reminder;
        String hexString;
        String temp = String.valueOf(colourValue[0].Colour__c).replace('.0', '');
        Integer colourValueInteger = Integer.valueOf(temp);

        while (colourValueInteger > 0) {
            reminder = Math.mod(colourValueInteger, 16);

            hexString = chars[reminder] + hexString;

            colourValueInteger = colourValueInteger / 16;
        }
        hexString = hexString.replace('null', '');
        hexString = '#0' + hexString;

        return hexString;
    }

}