src/objects/Trial__c.object
<CustomObject>
    <fields>
        <fullName>End_point__c</fullName>
        <label>End point</label>
        <scale>7</scale>
        <type>Location</type>
    </fields>
    <fields>
        <fullName>Start_point__c</fullName>
        <label>Start point</label>
        <scale>7</scale>
        <type>Location</type>
    </fields>
    <label>Trial</label>
    <nameField>
        <label>Trial Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TrialCoordinatesExtension.cls
/**
 * Created by drang on 10/19/2018.
 */

public with sharing class TrialCoordinatesExtension {

        private Trial__c currentTrial;

        public TrialCoordinatesExtension(ApexPages.StandardController controller) {
            controller.addFields(new String[]{'Start_point__c','End_point__c'});
            currentTrial = (Trial__c) controller.getRecord();
        }

        public Trial__c getTrial(){
            return currentTrial;
        }
    }